version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/public
    user: "node"
